create table address (id bigint generated by default as identity, bulding_number varchar(255), flat_number varchar(255), postal_code varchar(255), street varchar(255), town varchar(255), primary key (id))
create table badge_archivements (badge_rank_id bigint not null, user_id bigint not null, date date, primary key (badge_rank_id, user_id))
create table badge_ranks (id bigint generated by default as identity, description varchar(255), points integer not null, rank integer, with_excess boolean not null, badge_id bigint not null, primary key (id))
create table badge_application (id bigint generated by default as identity, check_date date, checked boolean not null, creation_date date, positive boolean not null, address_id bigint, badge_rank_id bigint not null, user_id bigint not null, primary key (id))
create table badges (id bigint generated by default as identity, description varchar(255), kind varchar(255), primary key (id))
create table confirmation_token (token_id bigint generated by default as identity, confirmation_token varchar(255), created_date timestamp, user_id bigint not null, primary key (token_id))
create table localizations (id bigint generated by default as identity, name varchar(255), primary key (id))
create table route_states (id bigint generated by default as identity, end date, open boolean not null, points_back integer, points_there integer, start date, route_id bigint not null, primary key (id))
create table routes (id bigint generated by default as identity, description varchar(255), end_id bigint not null, start_id bigint not null, primary key (id))
create table trips (id bigint generated by default as identity, date date, description varchar(255), is_confirmed boolean not null, name varchar(255), localization_id bigint, user_id bigint not null, primary key (id))
create table trip_segment (route_id bigint not null, trip_id bigint not null, order_number integer, primary key (route_id, trip_id))
create table users (id bigint generated by default as identity, email varchar(255), is_enabled boolean not null, password varchar(255), primary key (id))
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table badge_archivements add constraint FKh59ti0yasue37t25j4lfk3r8e foreign key (badge_rank_id) references badge_ranks
alter table badge_archivements add constraint FK4or63fvf08tkb2p7ntowmaype foreign key (user_id) references users
alter table badge_ranks add constraint FKewct7xe5mf29n8fewuloulyeo foreign key (badge_id) references badges
alter table badge_application add constraint FKd6ifgh4srgtumeuahuyani1pg foreign key (address_id) references address
alter table badge_application add constraint FK8bxv6vc266k8tkiy1uj2ex7tg foreign key (badge_rank_id) references badge_ranks
alter table badge_application add constraint FKnvapq27nwcnrdurbr22h2i15u foreign key (user_id) references users
alter table confirmation_token add constraint FKah4p1rycwibwm6s9bsyeckq51 foreign key (user_id) references users
alter table route_states add constraint FKvhk0jbegc1whty0sd5cv3398 foreign key (route_id) references routes
alter table routes add constraint FKaooql77fi37b141vhnua0a9p2 foreign key (end_id) references localizations
alter table routes add constraint FK12w1064u06k5r7a91oixweao8 foreign key (start_id) references localizations
alter table trips add constraint FK4aj585ubs27flptjlnif4twid foreign key (localization_id) references localizations
alter table trips add constraint FK8wb14dx6ed0bpp3planbay88u foreign key (user_id) references users
alter table trip_segment add constraint FK5sp7cl6ulxrmw6b132upys5l2 foreign key (route_id) references routes
alter table trip_segment add constraint FKc0af33r79cko88bpmdwomsirx foreign key (trip_id) references trips
